language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - pytest --doctest-modules --cov --cov-report term-missing tests/.
after_success:
    - coveralls
